name = "Meru's Modded Scraft"
author = "Dokji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0cc8c05288f8958ea96a2e2c737523794286226efdbd4c083183d6e802da7a0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
